services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    image: kolosovdv/frontend:v1
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db 
  backend:
    image: kolosovdv/backend:v1
    restart: always
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/media/
    depends_on:
      - frontend
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      #- ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend
volumes:
  static_value:
  media_value:
  postgres_data:
  result_build: